### ISSUE TITLE
Use Parameter field

### ISSUE THREAD

**Issue by gimmickyboot** [imchlorine/MykiBalance#1]
Hi.

Just a suggestion, you could replace `let cardNumber = "Your Myki Card"` with `let cardNumber = args.widgetParameter;` on line 15 so the user doesn't have to edit the code directly. Instead you would enter your MyKi card number in the widget parameter field. This would also allow for multiple MyKi's using the same Scriptable script without needing to copy/paste/edit the code into a new script.

Cheers,
Shannon

**Comment by rickyli-sosure** [comment]
Thanks for your suggestion.

**Comment by rickyli-sosure** [comment]
> Hi.
> 
> Just a suggestion, you could replace `let cardNumber = "Your Myki Card"` with `let cardNumber = args.widgetParameter;` on line 15 so the user doesn't have to edit the code directly. Instead you would enter your MyKi card number in the widget parameter field. This would also allow for multiple MyKi's using the same Scriptable script without needing to copy/paste/edit the code into a new script.
> 
> Cheers,
> Shannon

Thanks for your suggestion!

**Comment by imchlorine** [comment]
> Hi.
> 
> Just a suggestion, you could replace `let cardNumber = "Your Myki Card"` with `let cardNumber = args.widgetParameter;` on line 15 so the user doesn't have to edit the code directly. Instead you would enter your MyKi card number in the widget parameter field. This would also allow for multiple MyKi's using the same Scriptable script without needing to copy/paste/edit the code into a new script.
> 
> Cheers,
> Shannon

Thanks for your suggestion!
